In [1]:
import numpy as np
import pandas as pd
%run Caminhos.ipynb

tabela_base_gerada = pd.read_parquet(f'{pasta_hierarquia}{caminho_tabela_base_gerada_parquet}')
tabela_especificacao_ind_O_E = pd.read_parquet(f'{pasta_hierarquia}{caminho_especificacao_ind_O_E_parquet}')

Erro ao conectar: ORA-12545: Connect failed because target host or object does not exist
Help: https://docs.oracle.com/error-help/db/ora-12545/

BASE DE DADOS COMPARATIVA PAÍS

In [2]:
# Filtro por escola
BASE_GERADA_pais = tabela_base_gerada[(tabela_base_gerada['Resultado Comparativo'].str.contains("SIM")) & (tabela_base_gerada['Hierarquia'] == "Pais")]

# Adicionar a nova coluna 'TipoIndicadorEstPro' com a informação 'Manual' em todas as linhas

BASE_GERADA_pais = BASE_GERADA_pais[['Codigo Indicador', 'Ano', 'Mes_Referente', 'Pais', 'Quantidade', 'Data Cadastro', 'Hierarquia']]

# Agrupar pelo 'Codigo Indicador', 'Ano', 'Mes_Referente' e pegar a linha com a data mais recente e o maior Mes_Referente
result_pais = BASE_GERADA_pais.loc[
    BASE_GERADA_pais.sort_values(by=['Data Cadastro', 'Mes_Referente'], ascending=[False, False])
    .groupby(['Codigo Indicador', 'Ano', 'Hierarquia'])
    .head(1).index
]

result_pais['Codigo Indicador'] = result_pais['Codigo Indicador'].astype(int)

# Renomear duas colunas ao mesmo tempo
result_pais = result_pais.rename(columns={'Quantidade': 'Quantidade País'})

# Agrupar pelo 'Codigo Indicador', 'Ano', e 'Mes_Referente', e pegar o índice das linhas com a data mais recente
result_pais = result_pais.loc[result_pais.groupby(['Codigo Indicador', 'Ano', 'Hierarquia'])['Data Cadastro'].idxmax()]

result_pais = result_pais.drop(['Mes_Referente', 'Data Cadastro', 'Hierarquia'], axis=1)

# Exibir o DataFrame
display(result_pais)

       Codigo Indicador   Ano    Pais  Quantidade País
2462                 61  2022  Brasil     1.950000e-01
2463                 61  2023  Brasil     2.110000e-01
2482                 66  2022  Brasil     6.020000e-02
2483                 66  2023  Brasil     6.500000e-02
6962                 72  2022  Brasil     0.000000e+00
2502                159  2022  Brasil     1.476140e+07
2503                159  2023  Brasil     1.418089e+07
2553                182  2023  Brasil     4.130000e-02
2538                197  2022  Brasil     4.400000e-02
2539                197  2023  Brasil     5.200000e-02
2466               2202  2022  Brasil     1.650000e-01
2467               2202  2023  Brasil     1.870000e-01
2488               2207  2022  Brasil     5.640000e-02
2489               2207  2023  Brasil     6.220000e-02
6932               2210  2023  Brasil     3.002504e+06
6933               2210  2024  Brasil     4.100250e+06
2494               2213  2022  Brasil     8.539010e+05
2495               2213  2023  Brasil     9.212480e+05
2508               2214  2022  Brasil     3.600000e-01
2509               2214  2023  Brasil     5.600000e-01
2545               2217  2022  Brasil     4.200000e-02
2550               2217  2023  Brasil     5.200000e-02
20420              2217  2024  Brasil     4.400000e-02
2547               2218  2022  Brasil     8.900000e-02
2548               2218  2023  Brasil     8.900000e-02
20421              2218  2024  Brasil     7.800000e-02
7399               2221  2022  Brasil     9.300000e-01
2470               2232  2022  Brasil     4.655060e+05
2471               2232  2023  Brasil     4.962420e+05
2531               2239  2022  Brasil     2.695400e+02
13835              2239  2023  Brasil     2.699300e+02
2533               2240  2022  Brasil     2.758900e+02
13833              2240  2023  Brasil     2.769100e+02
2535               2241  2021  Brasil     2.623700e+02
13836              2241  2023  Brasil     2.643100e+02
2537               2242  2022  Brasil     2.708500e+02
13834              2242  2023  Brasil     2.728800e+02
2450               2258  2022  Brasil     3.900000e+00
10996              2258  2023  Brasil     4.100000e+00
10999              2259  2022  Brasil     4.200000e+00
13853              2259  2023  Brasil     4.300000e+00

BASE DE DADOS COMPARATIVA REGIÃO

In [3]:
# Filtro por escola
BASE_GERADA_regiao = tabela_base_gerada[(tabela_base_gerada['Resultado Comparativo'].str.contains("SIM")) & (tabela_base_gerada['Hierarquia'] == "Regiao")]

# Adicionar a nova coluna 'TipoIndicadorEstPro' com a informação 'Manual' em todas as linhas

BASE_GERADA_regiao = BASE_GERADA_regiao[['Codigo Indicador', 'Ano', 'Mes_Referente', 'Regiao', 'Quantidade', 'Data Cadastro', 'Hierarquia']]

# Agrupar pelo 'Codigo Indicador', 'Ano', 'Mes_Referente' e pegar a linha com a data mais recente e o maior Mes_Referente
result_regiao = BASE_GERADA_regiao.loc[
    BASE_GERADA_regiao.sort_values(by=['Data Cadastro', 'Mes_Referente'], ascending=[False, False])
    .groupby(['Codigo Indicador', 'Ano', 'Hierarquia'])
    .head(1).index
]

result_regiao['Codigo Indicador'] = result_regiao['Codigo Indicador'].astype(int)

# Renomear duas colunas ao mesmo tempo
result_regiao = result_regiao.rename(columns={'Quantidade': 'Quantidade Regiao'})

# Agrupar pelo 'Codigo Indicador', 'Ano', e 'Mes_Referente', e pegar o índice das linhas com a data mais recente
result_regiao = result_regiao.loc[result_regiao.groupby(['Codigo Indicador', 'Ano', 'Hierarquia'])['Data Cadastro'].idxmax()]

result_regiao = result_regiao.drop(['Mes_Referente', 'Data Cadastro', 'Hierarquia'], axis=1)

# Exibir o DataFrame
display(result_regiao)

       Codigo Indicador   Ano    Regiao  Quantidade Regiao
2461                 61  2022  Nordeste       2.910000e-01
2460                 61  2023  Nordeste       3.430000e-01
2484                 66  2022  Nordeste       1.241000e-01
2485                 66  2023  Nordeste       1.349000e-01
2504                159  2022  Nordeste       2.984453e+06
2505                159  2023  Nordeste       2.841729e+06
2540                197  2022  Nordeste       6.200000e-02
2541                197  2023  Nordeste       6.300000e-02
2468               2202  2022  Nordeste       2.380000e-01
2469               2202  2023  Nordeste       2.830000e-01
2490               2207  2022  Nordeste       1.119000e-01
2491               2207  2023  Nordeste       1.232000e-01
2496               2213  2022  Nordeste       3.527840e+05
2497               2213  2023  Nordeste       3.834440e+05
2510               2214  2022  Nordeste       2.930000e-01
2511               2214  2023  Nordeste       5.020000e-01
20427              2217  2024     Norte       7.000000e-02
20422              2218  2024     Norte       1.270000e-01
2472               2232  2022  Nordeste       8.144800e+04
2473               2232  2023  Nordeste       9.316500e+04
2525               2239  2022  Nordeste       2.610600e+02
13849              2239  2023  Nordeste       2.793200e+02
13851              2240  2023  Nordeste       2.795200e+02
15814              2241  2021  Nordeste       1.986600e+02
13850              2241  2023  Nordeste       2.056100e+02
2529               2242  2022  Nordeste       2.597100e+02
13852              2242  2023  Nordeste       2.784700e+02
2477               2258  2022  Nordeste       3.800000e+00
10997              2258  2023  Nordeste       4.080000e+00
11001              2259  2022  Nordeste       3.900000e+00
13854              2259  2023  Nordeste       4.470000e+00

BASE DE DADOS COMPARATIVA - MELHOR ESTADO DO BRASIL

In [4]:
# Filtro por escola
BASE_GERADA = tabela_base_gerada[(tabela_base_gerada['Resultado Comparativo'].str.contains("SIM")) & (tabela_base_gerada['Hierarquia'] == "Estado")]

# Adicionar a nova coluna 'TipoIndicadorEstPro' com a informação 'Manual' em todas as linhas

BASE_GERADA = BASE_GERADA[['Codigo Indicador', 'Ano', 'Mes_Referente', 'Id Estado', 'Estado', 'Quantidade', 'Data Cadastro', 'Hierarquia']]

# Agrupar pelo 'Codigo Indicador', 'Ano', 'Mes_Referente' e pegar a linha com a data mais recente e o maior Mes_Referente
melhor_result_estado = BASE_GERADA.loc[
    BASE_GERADA.sort_values(by=['Data Cadastro', 'Mes_Referente'], ascending=[False, False])
    .groupby(['Codigo Indicador', 'Ano', 'Hierarquia'])
    .head(1).index
]

melhor_result_estado['Codigo Indicador'] = melhor_result_estado['Codigo Indicador'].astype(int)

# Renomear duas colunas ao mesmo tempo
melhor_result_estado = melhor_result_estado.rename(columns={'Estado': 'Melhor Estado', 'Quantidade': 'Melhor Quantidade'})

# Agrupar pelo 'Codigo Indicador', 'Ano', e 'Mes_Referente', e pegar o índice das linhas com a data mais recente
melhor_result_estado = melhor_result_estado.loc[melhor_result_estado.groupby(['Codigo Indicador', 'Ano', 'Hierarquia'])['Data Cadastro'].idxmax()]

melhor_result_estado = melhor_result_estado.drop(['Mes_Referente', 'Data Cadastro', 'Hierarquia'], axis=1)
#melhor_result_estado = melhor_result_estado[(melhor_result_estado["Codigo Indicador"] == 2266)]
# Exibir o DataFrame
display(melhor_result_estado)

# salvar os dados em um arquivo csv
#%timeit melhor_result_estado.to_csv(f'{pasta_hierarquia}{caminho_teste1}')

       Codigo Indicador   Ano  Id Estado   Melhor Estado  Melhor Quantidade
2459                 61  2022       26.0      PERNAMBUCO       6.380000e-01
2458                 61  2023       26.0      PERNAMBUCO       6.830000e-01
20156                61  2024       13.0        AMAZONAS       2.404760e-01
20129                65  2024       12.0            ACRE       6.000000e+00
20183                66  2024       13.0        AMAZONAS       2.368700e-02
19832                67  2024       12.0            ACRE       1.492600e+04
2506                159  2022       35.0       SÃO PAULO       3.715952e+06
2507                159  2023       35.0       SÃO PAULO       3.672009e+06
19724               159  2024       12.0            ACRE       1.374590e+05
2542                197  2022       35.0       SÃO PAULO       1.700000e-02
2543                197  2023       35.0       SÃO PAULO       2.200000e-02
20048              2197  2024       12.0            ACRE       3.651800e+04
20075              2199  2024       12.0            ACRE       6.200000e+01
2464               2202  2022       23.0           CEARÁ       4.640000e-01
2465               2202  2023       23.0           CEARÁ       5.230000e-01
20237              2202  2024       13.0        AMAZONAS       1.277760e-01
19859              2212  2024       12.0            ACRE       7.200000e+01
2500               2213  2022       35.0       SÃO PAULO       2.282050e+05
2501               2213  2023       35.0       SÃO PAULO       2.218690e+05
19886              2213  2024       12.0            ACRE       3.256000e+03
2514               2214  2022       42.0  SANTA CATARINA       5.500000e-01
2515               2214  2023       23.0           CEARÁ       8.500000e-01
2546               2217  2023       22.0           PIAUÍ       4.100000e-02
20393              2217  2024       11.0        RONDÔNIA       4.900000e-02
20366              2218  2024       11.0        RONDÔNIA       6.700000e-02
2474               2232  2022       35.0       SÃO PAULO       8.812000e+04
2475               2232  2023       35.0       SÃO PAULO       9.171700e+04
20021              2232  2024       12.0            ACRE       1.143600e+04
2519               2239  2021       41.0          PARANÁ       2.455300e+02
2520               2239  2023       23.0           CEARÁ       2.555600e+02
2523               2240  2022       41.0          PARANÁ       2.996700e+02
13837              2240  2023       41.0          PARANÁ       2.888000e+02
15813              2241  2021       41.0          PARANÁ       2.574600e+02
13839              2241  2023       23.0           CEARÁ       2.700300e+02
2521               2242  2022       31.0    MINAS GERAIS       3.045800e+02
13838              2242  2023       52.0           GOIÁS       2.846400e+02
19778              2246  2024       12.0            ACRE       3.575000e+04
2479               2258  2022       52.0           GOIÁS       4.500000e+00
20339              2258  2023       11.0        RONDÔNIA       4.000000e+00
13844              2259  2022       41.0          PARANÁ       4.800000e+00
13848              2259  2023       41.0          PARANÁ       4.900000e+00
21140              2266  2024       12.0            ACRE       4.824000e-03
19371              2287  2024       35.0       SÃO PAULO       2.455000e-01
20210              2294  2024       13.0        AMAZONAS       8.319600e-02
19913              2302  2024       12.0            ACRE       9.564000e+03
19940              2303  2024       12.0            ACRE       6.481000e+03
20261              2304  2024       12.0            ACRE       8.990000e+03
19994              2305  2024       12.0            ACRE       6.623000e+03
20313              2306  2024       12.0            ACRE       8.622000e+03
19967              2307  2024       12.0            ACRE       1.148600e+04
20287              2308  2024       12.0            ACRE       1.476000e+03
19805              2309  2024       12.0            ACRE       8.597000e+03
19751              2310  2024       12.0            ACRE       1.756400e+04
20102              2318  2024       12.0            ACRE       1.110000e+02

BASE DE DADOS COMPARATIVA ESTADO

In [5]:
# Filtro por escola
BASE_GERADA = tabela_base_gerada[(tabela_base_gerada['Resultado Comparativo'].str.contains("NÃO")) & (tabela_base_gerada['Hierarquia'] == "Estado")]

# Adicionar a nova coluna 'TipoIndicadorEstPro' com a informação 'Manual' em todas as linhas

BASE_GERADA = BASE_GERADA[['Codigo Indicador', 'Ano', 'Mes_Referente', 'Id Estado', 'Estado', 'Quantidade', 'Data Cadastro', 'Hierarquia']]

# Agrupar pelo 'Codigo Indicador', 'Ano', 'Mes_Referente' e pegar a linha com a data mais recente e o maior Mes_Referente
result_piaui = BASE_GERADA.loc[
    BASE_GERADA.sort_values(by=['Data Cadastro', 'Mes_Referente'], ascending=[False, False])
    .groupby(['Codigo Indicador', 'Ano', 'Hierarquia'])
    .head(1).index
]

result_piaui['Codigo Indicador'] = result_piaui['Codigo Indicador'].astype(int)

result_piaui = result_piaui.drop(['Mes_Referente', 'Data Cadastro', 'Hierarquia'], axis=1)
#result_piaui = result_piaui[(result_piaui["Codigo Indicador"] == 2266)]

# Exibir o DataFrame
display(result_piaui)

# salvar os dados em um arquivo csv
#%timeit melhor_result_estado.to_csv(f'{pasta_hierarquia}{caminho_teste2}')

       Codigo Indicador   Ano  Id Estado Estado    Quantidade
19370              2287  2024       22.0  PIAUÍ  5.170000e-02
19166              2283  2024       22.0  PIAUÍ  5.650000e+02
19165              2228  2024       22.0  PIAUÍ  1.378074e+08
19164               150  2024       22.0  PIAUÍ  4.560000e-01
19162              2280  2023       22.0  PIAUÍ  1.100000e+02
...                 ...   ...        ...    ...           ...
1                  2221  2023       22.0  PIAUÍ  9.880000e-01
2                  2220  2022       22.0  PIAUÍ  3.160000e-01
3                  2220  2023       22.0  PIAUÍ  3.690000e-01
17524              2282  2023       22.0  PIAUÍ  1.000000e+00
17297              2281  2024       22.0  PIAUÍ  8.264000e-01

[481 rows x 5 columns]

Melhor estado atualizado

In [6]:
# Filtrando os códigos que estão em `melhor_result_estado`
codigos_melhor_estado = melhor_result_estado['Codigo Indicador'].unique()

# Excluindo esses códigos de `result_piaui`
result_piaui_filtrado = result_piaui[~result_piaui['Codigo Indicador'].isin(codigos_melhor_estado)]

# Concatenando as duas tabelas
final_df = pd.concat([melhor_result_estado, result_piaui_filtrado], ignore_index=True)

# Removendo duplicatas, priorizando o "Resultado Melhor Estado"
final_df = final_df.drop_duplicates(keep='first')

# Preenchendo valores ausentes em "Melhor Estado" com os valores da coluna "Estado"
final_df['Melhor Estado'] = final_df['Melhor Estado'].fillna(final_df['Estado'])
final_df['Melhor Quantidade'] = final_df['Melhor Quantidade'].fillna(final_df['Quantidade'])

# Removendo a coluna "Estado", já que a informação agora está consolidada em "Melhor Estado"
final_df = final_df.drop(columns=['Estado', 'Quantidade'])
#final_df = final_df[(final_df["Codigo Indicador"] == 2266)]
display(final_df)
# salvar os dados em um arquivo csv
#%timeit final_df.to_csv(f'{pasta_hierarquia}{caminho_teste2}')

     Codigo Indicador   Ano  Id Estado Melhor Estado  Melhor Quantidade
0                  61  2022       26.0    PERNAMBUCO           0.638000
1                  61  2023       26.0    PERNAMBUCO           0.683000
2                  61  2024       13.0      AMAZONAS           0.240476
3                  65  2024       12.0          ACRE           6.000000
4                  66  2024       13.0      AMAZONAS           0.023687
..                ...   ...        ...           ...                ...
440              2221  2023       22.0         PIAUÍ           0.988000
441              2220  2022       22.0         PIAUÍ           0.316000
442              2220  2023       22.0         PIAUÍ           0.369000
443              2282  2023       22.0         PIAUÍ           1.000000
444              2281  2024       22.0         PIAUÍ           0.826400

[445 rows x 5 columns]

Tabela Comparativa

In [7]:
# Supondo que temos dois DataFrames: df1 e df2

tab_comparativa = result_piaui.merge(final_df, on=['Codigo Indicador', 'Ano'], how='left')
tab_comparativa = tab_comparativa.merge(result_regiao, on=['Codigo Indicador', 'Ano'], how='left')
tab_comparativa = tab_comparativa.merge(result_pais, on=['Codigo Indicador', 'Ano'], how='left')

#Avaliar ERRO relacionado a coluna 'Id Estado'

display(tab_comparativa)

,Codigo Indicador,Ano,Id Estado_x,Estado,Quantidade,Id Estado_y,Melhor Estado,Melhor Quantidade,Regiao,Quantidade Regiao,Pais,Quantidade País
0,2287,2024,22.0,PIAUÍ,5.170000e-02,35.0,SÃO PAULO,2.455000e-01,NaN,NaN,NaN,NaN
1,2283,2024,22.0,PIAUÍ,5.650000e+02,22.0,PIAUÍ,5.650000e+02,NaN,NaN,NaN,NaN
2,2228,2024,22.0,PIAUÍ,1.378074e+08,22.0,PIAUÍ,1.378074e+08,NaN,NaN,NaN,NaN
3,150,2024,22.0,PIAUÍ,4.560000e-01,22.0,PIAUÍ,4.560000e-01,NaN,NaN,NaN,NaN
4,2280,2023,22.0,PIAUÍ,1.100000e+02,22.0,PIAUÍ,1.100000e+02,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
476,2221,2023,22.0,PIAUÍ,9.880000e-01,22.0,PIAUÍ,9.880000e-01,NaN,NaN,NaN,NaN
477,2220,2022,22.0,PIAUÍ,3.160000e-01,22.0,PIAUÍ,3.160000e-01,NaN,NaN,NaN,NaN
478,2220,2023,22.0,PIAUÍ,3.690000e-01,22.0,PIAUÍ,3.690000e-01,NaN,NaN,NaN,NaN
479,2282,2023,22.0,PIAUÍ,1.000000e+00,22.0,PIAUÍ,1.000000e+00,NaN,NaN,NaN,NaN
480,2281,2024,22.0,PIAUÍ,8.264000e-01,22.0,PIAUÍ,8.264000e-01,NaN,NaN,NaN,NaN

Tabela de Especificação de Indicadores

In [8]:
tabela_especificacao_ind_O_E = tabela_especificacao_ind_O_E[["Codigo Indicador", "MetaMes", "TipoIndicadorEstPro", "UnidadeMedida", "Ano_Meta", "Mes_Meta", "GlossarioIndicador"]]

# Agrupar pelo 'Codigo Indicador', 'Ano', 'Mes_Referente' e pegar a linha com a data mais recente e o maior Mes_Referente
tabela_especificacao_ind_O_E = tabela_especificacao_ind_O_E.loc[
    tabela_especificacao_ind_O_E.sort_values(by=['Mes_Meta'], ascending=[False])
    .groupby(['Codigo Indicador', 'Ano_Meta'])
    .head(1).index
]

# Verificando as colunas antes de renomear
#tabela_especificacao_ind_O_E = tabela_especificacao_ind_O_E[tabela_especificacao_ind_O_E['Codigo Indicador'] == 177]
#display(tabela_especificacao_ind_O_E)
# Renomear a coluna de contagem para diferenciar
tabela_especificacao_ind_O_E.rename(columns={'Ano_Meta': 'Ano'}, inplace=True)

tabela_especificacao_ind_O_E = tabela_especificacao_ind_O_E[tabela_especificacao_ind_O_E['GlossarioIndicador'].str.contains("Compromisso", case=False)]

# Filtra o DataFrame removendo as linhas que contenham "EXCLUIR" na coluna GlossarioIndicador
tabela_especificacao_ind_O_E = tabela_especificacao_ind_O_E[~tabela_especificacao_ind_O_E['GlossarioIndicador'].str.contains("EXCLUIR", na=False)]

tabela_especificacao_ind_O_E = tabela_especificacao_ind_O_E.drop_duplicates()

# Mesclar os DataFrames para adicionar as colunas com o cálculo
tab_comparativo_gov = tabela_especificacao_ind_O_E.merge(tab_comparativa, on=['Codigo Indicador', 'Ano'], how='left')

tab_comparativo_gov['MetaMes'] = tab_comparativo_gov['MetaMes'].fillna(np.nan)
#tab_comparativo_gov = tab_comparativo_gov[(tab_comparativo_gov["Codigo Indicador"] == 73)]
#tab_comparativo_gov = tab_comparativo_gov[(tab_comparativo_gov["Ano_Meta"] == 2022)]

display(tab_comparativo_gov)

tab_comparativo_gov.to_csv(f'{pasta_hierarquia}{caminho_base_comparativa_csv}', index=False)
tab_comparativo_gov.to_parquet(f'{pasta_hierarquia}{caminho_base_comparativa_parquet}', index=False)

,Codigo Indicador,MetaMes,TipoIndicadorEstPro,UnidadeMedida,Ano,Mes_Meta,GlossarioIndicador,Id Estado_x,Estado,Quantidade,Id Estado_y,Melhor Estado,Melhor Quantidade,Regiao,Quantidade Regiao,Pais,Quantidade País
0,61,90.0,E,%,2026,12,<p>Att A<br></p><p>Compromisso 4</p><p><br></p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2222,NaN,E,Nº,2022,12,<p>Att M</p><p>Compromisso 3</p><p>formula N° ...,22.0,PIAUÍ,6.0,22.0,PIAUÍ,6.0,NaN,NaN,NaN,NaN
2,170,250.0,E,Nº,2026,12,<p>Att M</p><p>Compromisso 2</p><p>formula Qua...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,170,200.0,E,Nº,2025,12,<p>Att M</p><p>Compromisso 2</p><p>formula Qua...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,170,160.0,E,Nº,2024,12,<p>Att M</p><p>Compromisso 2</p><p>formula Qua...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713,90,80.0,O,%,2024,12,<p>Att M</p><p>Compromisso 4</p><p>formula&nbs...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
714,2319,NaN,E,R$,2022,12,<p>Att M</p><p>Compromisso 5</p><p>formula Val...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
715,2319,NaN,E,R$,2023,12,<p>Att M</p><p>Compromisso 5</p><p>formula Val...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
716,67,NaN,E,Nº,2025,4,<p>Att A</p><p>formula N° de matrículas EJA em...,22.0,PIAUÍ,38619.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
717,190,NaN,E,Nº,2025,1,<p>Att M<br></p><p>Compromisso 7</p><p><br></p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN